### ISSUE TITLE
make sure there is a trailing slash on the discourse url

### ISSUE THREAD

**Issue by oblakeerickson** [oblakeerickson/jekyll_discourse_comments#1]
When I initially setup my discourse site in the _config.yml file, I didn't include a trailing slash `/` on the end of the url. I had 'http://discuss.blakeerickson.com` and I needed to have 'http://discuss.blakeerickson.com/'.

WIthout the slash the comments won't work.

**Comment by parkr** [comment]
`File.join` might come in handy here, no?

**Comment by oblakeerickson** [comment]
I think it might!
