### ISSUE TITLE
Octopress integration?

### ISSUE THREAD

**Issue by justin808** [oblakeerickson/jekyll_discourse_comments#2]
Has this plugin been tried with Octopress?

**Comment by oblakeerickson** [comment]
I have not tried it with Octopress. It looks like other jekyll plugins work so I bet it will. If you get a chance to try it out, let me know.

**Comment by oblakeerickson** [comment]
Looks like you got it working with Octopress: http://www.railsonmaui.com/blog/2014/09/27/updating-to-jekyll-2-and-discourse-for-comments/

**Comment by justin808** [comment]
Not quite @oblakeerickson 

The answer is that EVERY article needs a More divider. If you place the whole article in discourse, then trouble.

But the work around is fine.

**Comment by oblakeerickson** [comment]
Is this the issue where it says "Post A Comment" on the main page a bunch of times in a row or some other issue?

Is that a Jekyll issue and not specific to Octopress?

**Comment by justin808** [comment]
I'm not sure. The basic problem is that the integration example assumes that it's the only comment thread on the page, and it renders from the bottom of the blog article.
